services:
  fastapi:
    build: .
    depends_on:
      - elasticsearch
      - redis
    environment:
      - REDIS_HOST=redis
      - ELASTIC_HOST=elasticsearch
  nginx:
    image: 'nginx:1.19.2'
    depends_on:
      - fastapi
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    restart: always
  redis:
    image: 'redis:6.2'
  elasticsearch:
    image: 'elasticsearch:7.16.1'
    environment:
      - discovery.type=single-node
  pytest:
    build:
      context: .
      dockerfile: Docker_pytest
    volumes:
      - ./tests:/logs