version: '2'
services:
  etl:
    build:
      context: .
      dockerfile: Docker_ETL
    depends_on:
      - elasticsearch
      - postgres
    environment:
      - refresh=5
  fastapi:
    build: .
    depends_on:
      - elasticsearch
      - redis
    environment:
      - REDIS_HOST=redis
      - ELASTIC_HOST=elasticsearch
  nginx:
    image: 'nginx:1.19.2'
    depends_on:
      - fastapi
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    restart: always
  redis:
    image: 'redis:6.2'
  elasticsearch:
    image: 'elasticsearch:7.16.1'
    volumes:
      - 'movies_es:/usr/share/elasticsearch/data'
    environment:
      - discovery.type=single-node
  postgres:
    image: 'postgres:13'
    volumes:
      - 'movies_db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
volumes:
  movies_db:
    external: true
  movies_es:
    external: true
