version: '2'
services:
  etl:
    build:
      context: .
      dockerfile: Docker_ETL
    depends_on:
      - elasticsearch
      - postgres
    environment:
      - refresh=5
  redis:
    image: 'redis:6.2'
    ports:
      - '6379:6379'
  elasticsearch:
    image: 'elasticsearch:7.16.1'
    ports:
      - '9200:9200'
    volumes:
      - 'movies_es:/usr/share/elasticsearch/data'
    environment:
      - discovery.type=single-node
  postgres:
    image: 'postgres:13'
    volumes:
      - 'movies_db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=movies_database
      - DB_USER=postgres
      - DB_PASSWORD=1234
    ports:
      - '5432:5432'
volumes:
  movies_db:
    external: true
  movies_es:
    external: true
